name: Super-Linter

# Run this workflow every time a new commit pushed to our repository
# and on pull requests.
on: [push, pull_request]

jobs:

  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of our repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # `.ts` files are not TypeScript files in this repository
          # but translation files.
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          # Qt has a custom CSS syntax
          VALIDATE_CSS: false
          # TODO
          VALIDATE_MARKDOWN: false
          VALIDATE_BASH: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_EDITORCONFIG: false
